### ISSUE TITLE
Build image for v0.8.0

### ISSUE THREAD

**Issue by djjudas21** [prometheus-community/smartctl_exporter#78] opened 2022-10-05 09:00 UTC
I see that there's a tagged release for [v0.8.0](https://github.com/prometheus-community/smartctl_exporter/releases/tag/v0.8.0) but no corresponding tag on [Docker Hub](https://hub.docker.com/r/prometheuscommunity/smartctl-exporter/tags). Please could you build and publish the new image? Thanks :slightly_smiling_face:

**Comment by SuperQ** [comment] 2022-10-05 11:54
This should actually be fixed with https://github.com/prometheus-community/smartctl_exporter/pull/77, but we need to re-tag the release to include it.

**Comment by SuperQ** [comment] 2022-10-05 11:56
Oh, it turns out, that syntax doesn't work as expected.

The problem is alpine doesn't tag their multi-arch images the same way Prometheus busybox does.

**Closed** 2022-10-05 16:18 UTC
