### ISSUE TITLE
Too early collect and panic

### ISSUE THREAD

**Issue by prologic** [prometheus-community/smartctl_exporter#40] opened 2022-04-07 10:30 UTC
See:

```#
Apr 07 20:30:17 vz1.mills.io smartctl_exporter[10911]: [Error] Too early collect called for device /dev/sda
Apr 07 20:30:17 vz1.mills.io smartctl_exporter[10911]: [Error] Too early collect called for device /dev/sdb
Apr 07 20:30:17 vz1.mills.io smartctl_exporter[10911]: [Error] Too early collect called for device /dev/sdc
Apr 07 20:30:17 vz1.mills.io smartctl_exporter[10911]: panic: runtime error: index out of range [0] with length 0
Apr 07 20:30:17 vz1.mills.io smartctl_exporter[10911]: goroutine 44 [running]:
Apr 07 20:30:17 vz1.mills.io smartctl_exporter[10911]: main.(*SMARTctlInfo).mineVersion(0xc0000b5ec0)
Apr 07 20:30:17 vz1.mills.io smartctl_exporter[10911]:         /mnt/Sheridan/sheridan/sheridan/smartctl_exporter/smartctlinfo.go:46 +0x942
Apr 07 20:30:17 vz1.mills.io smartctl_exporter[10911]: main.(*SMARTctlInfo).Collect(...)
Apr 07 20:30:17 vz1.mills.io smartctl_exporter[10911]:         /mnt/Sheridan/sheridan/sheridan/smartctl_exporter/smartctlinfo.go:35
Apr 07 20:30:17 vz1.mills.io smartctl_exporter[10911]: main.SMARTctlManagerCollector.Collect(0xc0002cc120)
Apr 07 20:30:17 vz1.mills.io smartctl_exporter[10911]:         /mnt/Sheridan/sheridan/sheridan/smartctl_exporter/main.go:37 +0x1c1
Apr 07 20:30:17 vz1.mills.io smartctl_exporter[10911]: github.com/prometheus/client_golang/prometheus.(*wrappingCollector).Collect.func1(0xc00021a6c0, 0xc0002cc120)
Apr 07 20:30:17 vz1.mills.io smartctl_exporter[10911]:         /mnt/Sheridan/sheridan/sheridan/smartctl_exporter/vendor/src/github.com/prometheus/client_golang/prometheus/wrap.go:129 +0x3d
```

**Comment by lahwaacz** [comment] 2022-04-08 06:34
Duplicate of #13 and #19.

**Comment by prologic** [comment] 2022-04-08 06:37
> Duplicate of #13 and #19.

Yes I realized after the fact sorry about that !

**Comment by lahwaacz** [comment] 2022-08-05 06:39
#13 was fixed via #18. Can this be closed?

**Comment by kfox1111** [comment] 2022-08-05 17:31
I can confirm, the new version seems to have the issue fixed.

**Comment by lahwaacz** [comment] 2022-11-06 12:19
This should be closed.

**Closed** 2022-11-06 13:18 UTC
