### ISSUE TITLE
Add build for aarch64 architecture

### ISSUE THREAD

**Issue by varac** [prometheus-community/smartctl_exporter#119] opened 2023-04-23 07:55 UTC
Please add a aarch64 build for upcoming releases, so SBC boards like [Rockpro64](https://www.pine64.org/rockpro64/) are supported. Thanks !

**Comment by enmanuelmoreira** [comment] 2023-11-13 00:39
That would be great! Thinking about arm64 ampere processors and raspberry pi 4-5 devices

**Comment by alex-dna-tech** [comment] 2024-11-02 08:54
Duplicate of #105

**Closed** 2024-12-15 21:11 UTC
