### ISSUE TITLE
Missing smartctl flags

### ISSUE THREAD

**Issue by intelfx** [prometheus-community/smartctl_exporter#190] opened 2023-12-31 20:55 UTC
I see from the code that it supports collecting a lot more metrics than the included `smartctl` call will generate. For instance, this is supposed to collect the ATA devstat log:

https://github.com/prometheus-community/smartctl_exporter/blob/3463e4fcd5a3e0bd5b273a07c64231df3decb83d/smartctl.go#L445

However, `smartctl --json --info --health --attributes` will never print it. There's also support for other log pages which, again, are absent in the smartctl output as invoked.

Consider switching to `smartctl --xall`.

**Comment by lahwaacz** [comment] 2023-12-31 21:32
This is a duplicate of https://github.com/prometheus-community/smartctl_exporter/issues/92

**Comment by NiceGuyIT** [comment] 2023-12-31 23:31
@intelfx Join the conversation in #92.

**Closed by NiceGuyIT** 2023-12-31 23:31 UTC
